# Generated by Django 2.1.1 on 2019-10-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191003_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Review'),
        ),
    ]
