# Generated by Django 2.1.1 on 2019-10-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191003_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='products',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='products',
            name='review',
        ),
        migrations.RemoveField(
            model_name='section',
            name='products',
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
        migrations.AddField(
            model_name='products',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
        migrations.AddField(
            model_name='products',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Basket'),
        ),
        migrations.AddField(
            model_name='review',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
    ]
