# Generated by Django 2.1.1 on 2019-10-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191003_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
    ]
