# Generated by Django 2.1.1 on 2019-10-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191016_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Basket'),
        ),
    ]
