# Generated by Django 2.1.1 on 2019-10-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.TextField(default=213),
            preserve_default=False,
        ),
    ]
