# Generated by Django 2.1.1 on 2019-10-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='basket',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
    ]
