# Generated by Django 2.0 on 2019-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191018_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='bas', to='app.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.ManyToManyField(blank=True, to='app.Article'),
        ),
    ]
